// Generated by CoffeeScript 1.8.0
var log;

$(document).ready(function() {
  var api;
  api = new GuildWars2API;
  api.GetMaps().then(function(data) {
    return log('GetMaps succeed', data);
  });
  Promise.all([api.GetEventNames(), api.GetEventDetails()]).then(function(data) {
    return log('Promise.all succeed', data);
  });
  api.GetExchangeGems(-1).then(function(data) {
    return log("GetExchangeGems succeed - this shouldn't happen");
  }, function(error) {
    return log('GetExchangeGems error', error);
  });
  return api.GetItems().then(function(data) {
    log('1st in chain succeed');
    return api.GetItemDetails(data.items[0]);
  }).then(function(data) {
    return log('2nd in chain succeed', data);
  });
});

log = function() {
  var msg, _i, _len;
  for (_i = 0, _len = arguments.length; _i < _len; _i++) {
    msg = arguments[_i];
    console.log(msg);
  }
  return console.log('---');
};
